comp: v1 v2 v3 v4
	./v1
	./v2
	./v3
	./v4
v1: calculmatV1.c
	gcc -Wall calculmatV1.c -o v1 -fopenmp
v2: calculmatV2.c
	gcc -Wall calculmatV2.c -o v2 -fopenmp
v3: calculmatV3.c
	gcc -Wall calculmatV3.c -o v3 -fopenmp
v4: calculmatV4.c
	gcc -Wall calculmatV4.c -o v4 -fopenmp
